name: spycohubrestaurant
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  carousel_slider: ^4.2.1
  cached_network_image: ^3.3.1
  colorful_safe_area: ^1.0.0
  flutter_rating_bar: ^4.0.1
  animated_flip_counter: ^0.2.6
  percent_indicator: 3.0.1
  image_picker: ^1.0.7
  dotted_border: ^2.0.0+2
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  pin_code_fields: ^8.0.1
  flutter_switch: ^0.3.2
  fl_chart: ^0.66.2
  syncfusion_flutter_charts: ^25.1.37
  file_picker: ^6.0.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:


  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    #    - assets/notification.mp3/


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-Black.ttf
          weight: 900
        - asset: assets/font/Poppins-BlackItalic.ttf
          weight: 900
        - asset: assets/font/Poppins-Bold.ttf
          weight: 700
        - asset: assets/font/Poppins-BoldItalic.ttf
          weight: 700
        - asset: assets/font/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/font/Poppins-ExtraBoldItalic.ttf
          weight: 800
        - asset: assets/font/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/font/Poppins-ExtraLightItalic.ttf
          weight: 200
        - asset: assets/font/Poppins-Italic.ttf
          weight: 400
        - asset: assets/font/Poppins-Light.ttf
          weight: 300
        - asset: assets/font/Poppins-LightItalic.ttf
          weight: 300
        - asset: assets/font/Poppins-Medium.ttf
          weight: 500
        - asset: assets/font/Poppins-MediumItalic.ttf
          weight: 500
        - asset: assets/font/Poppins-Regular.ttf
          weight: 400
        - asset: assets/font/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/font/Poppins-SemiBoldItalic.ttf
          weight: 600
        - asset: assets/font/Poppins-Thin.ttf
          weight: 100
        - asset: assets/font/Poppins-ThinItalic.ttf
          weight: 100




